#!/usr/bin/env node
// ============================================================
// InsightMesh — Build Script
// ============================================================
// Reads GEMINI_API_KEY from .env and generates config.js
// Usage: node build.js
// ============================================================

const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, ".env");
const configPath = path.join(__dirname, "config.js");

// Parse .env file
function parseEnv(filePath) {
  const vars = {};
  if (!fs.existsSync(filePath)) {
    console.error("❌ .env file not found. Create one with: GEMINI_API_KEY=your_key_here");
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    vars[key] = value;
  }
  return vars;
}

const env = parseEnv(envPath);
const apiKey = env.GEMINI_API_KEY;

if (!apiKey || apiKey === "YOUR_API_KEY_HERE") {
  console.warn("⚠️  Warning: GEMINI_API_KEY is not set in .env — using placeholder.");
  console.warn("   Edit .env and set: GEMINI_API_KEY=your_actual_key");
}

const configContent = `// ============================================================
// InsightMesh Configuration (Auto-generated by build.js)
// ============================================================
// Do NOT edit this file directly. Update your .env file and
// re-run: node build.js
// ============================================================

const GEMINI_API_KEY = "${apiKey || "YOUR_API_KEY_HERE"}";
const GEMINI_MODEL = "gemini-2.5-flash";
const GEMINI_API_URL = \`https://generativelanguage.googleapis.com/v1beta/models/\${GEMINI_MODEL}:generateContent\`;
`;

fs.writeFileSync(configPath, configContent, "utf-8");
console.log("✅ config.js generated successfully.");
if (apiKey && apiKey !== "YOUR_API_KEY_HERE") {
  console.log("   API key: " + apiKey.slice(0, 6) + "…" + apiKey.slice(-4));
}
